<?php
require __DIR__.'/bootstrap.php';
gml_test_product_init();
wp_set_current_user(1);
GML_Installer::activate();
gml_db_assert(class_exists('GML_Item_Resolution'),'resource-local item resolution service exists');
update_option('gml_multilingual_enabled',true);
update_option('gml_languages',[['code'=>'de','enabled'=>true]]);
update_option('gml_source_lang','en');
update_option('blog_public','1');
update_option('gml_translation_paused',true);
global $wpdb;
$text='Current unresolved engineering label '.wp_generate_uuid4();
$id=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>'Resolution fixture']);
$other=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>'Shared fixture']);
$resource=GML_Resource_Identity::for_post($id);
$shared=GML_Resource_Identity::for_post($other);
$nodes=[['text'=>$text,'context_type'=>'text']];
GML_Resource_Manifest_Store::save_complete($resource,$nodes);
GML_Resource_Manifest_Store::save_complete($shared,$nodes);
$m=GML_Resource_Manifest_Store::get_by_key($resource->get_key());
$m2=GML_Resource_Manifest_Store::get_by_key($shared->get_key());
$wpdb->insert($wpdb->prefix.'gml_queue',['source_hash'=>md5($text),'source_text'=>$text,'source_lang'=>'en','target_lang'=>'de','context_type'=>'text','status'=>'failed','attempts'=>3,'error_message'=>'HTTP 400 historical','created_at'=>current_time('mysql')]);
$qid=(int)$wpdb->insert_id;
GML_Resource_Readiness::recalculate_resources([$m->id,$m2->id],['de']);
function resolution_policy($resource) {return GML_Public_Eligibility::get_status($resource,'de')['page_readiness'];}
$before=resolution_policy($resource);
gml_db_assert($before['unresolved_count']===1 && $before['keep_source_count']===0,'AI failure remains unresolved, never implicit keep source');
$token=GML_Item_Resolution::token(GML_Item_Resolution::snapshot($qid,$m->id));
$generation=GML_Page_Cache::generation();
$fail_cache=static function($sql){return strpos($sql,'SET option_value=GREATEST')!==false && strpos($sql,'gml_page_cache_generation')!==false ? 'SELECT * FROM gml_intentional_missing_table' : $sql;};
$suppressed=$wpdb->suppress_errors(true);
add_filter('query',$fail_cache);
$failed_decision=GML_Item_Resolution::decide($qid,$m->id,$token,'keep_source',false);
remove_filter('query',$fail_cache);
$wpdb->suppress_errors($suppressed);
gml_db_assert(is_wp_error($failed_decision) && !GML_Item_Resolution::snapshot($qid,$m->id)['decision'],'failed durable cache invalidation rolls back decision');
gml_db_assert(GML_Page_Cache::generation()===$generation,'failed decision never advances committed cache generation');
gml_db_assert(GML_Item_Resolution::decide($qid,$m->id,$token,'keep_source',false)===true,'explicit ordinary keep source is saved');
gml_db_assert(GML_Page_Cache::generation()>$generation && get_option(GML_Page_Cache::CLUSTER_PREFIX.$m->id,false)!==false,'successful decision records durable resource cache work');
$policy=resolution_policy($resource);
gml_db_assert($policy['translated_count']===0 && $policy['resolved_count']===1 && $policy['ready'],'keep source resolves but does not translate');
gml_db_assert(resolution_policy($shared)['unresolved_count']===1,'shared source decision never expands to another page');
$require_review=static function(){return true;};
add_filter('gml_translation_review_required',$require_review);
gml_db_assert(!GML_Public_Eligibility::is_eligible($resource,'de'),'keep source does not silently grant required human approval');
$review=GML_Resource_Approval::get_status($resource,'de');
gml_db_assert(!is_wp_error(GML_Resource_Approval::approve($resource,'de',1,'Explicit source review',GML_Resource_Approval::expected_snapshot($review))),'resolved source snapshot can be explicitly approved');
gml_db_assert(GML_Public_Eligibility::is_eligible($resource,'de'),'exact approved resolved snapshot satisfies optional review policy');
remove_filter('gml_translation_review_required',$require_review);
gml_db_assert(is_wp_error(GML_Item_Resolution::decide($qid,$m->id,$token,'revoke',false)),'old decision token cannot revoke a newer state');
$token=GML_Item_Resolution::token(GML_Item_Resolution::snapshot($qid,$m->id));
gml_db_assert(GML_Item_Resolution::decide($qid,$m->id,$token,'revoke',false)===true,'administrator can revoke exact current decision');
gml_db_assert(resolution_policy($resource)['unresolved_count']===1,'revocation returns the item to unresolved');
gml_db_assert(!GML_Resource_Approval::get_status($resource,'de')['snapshot_matches'],'revocation invalidates previous page approval');
$token=GML_Item_Resolution::token(GML_Item_Resolution::snapshot($qid,$m->id));
GML_Item_Resolution::decide($qid,$m->id,$token,'keep_source',false);
GML_Resource_Manifest_Store::save_complete($resource,[['text'=>$text.' updated','context_type'=>'text']]);
GML_Resource_Readiness::recalculate_resources([$m->id],['de']);
gml_db_assert(resolution_policy($resource)['keep_source_count']===0,'changed source manifest makes old keep source stale');
gml_db_assert((int)$wpdb->get_var('SELECT COUNT(*) FROM '.GML_Item_Resolution::table().' WHERE resource_id='.(int)$m->id)>=2,'decision and revocation audit retained');
gml_db_assert((bool)get_option('gml_translation_paused'),'human resolution never resumes global AI');
$critical='Current SEO title '.wp_generate_uuid4();
$wpdb->insert($wpdb->prefix.'gml_queue',['source_hash'=>md5($critical),'source_text'=>$critical,'source_lang'=>'en','target_lang'=>'de','context_type'=>'seo_title','status'=>'failed','attempts'=>3,'error_message'=>'protected_term','created_at'=>current_time('mysql')]);
$critical_id=(int)$wpdb->insert_id;
GML_Resource_Manifest_Store::save_complete($resource,[['text'=>$critical,'context_type'=>'seo_title']]);
GML_Resource_Readiness::recalculate_resources([$m->id],['de']);
$snapshot=GML_Item_Resolution::snapshot($critical_id,$m->id);
$token=GML_Item_Resolution::token($snapshot);
gml_db_assert(!resolution_policy($resource)['ready'] && resolution_policy($resource)['critical_unresolved_count']===1,'unresolved critical issue blocks SEO readiness');
gml_db_assert(is_wp_error(GML_Item_Resolution::decide($critical_id,$m->id,$token,'keep_source',false)),'critical keep source rejected without explicit confirmation');
gml_db_assert(GML_Item_Resolution::decide($critical_id,$m->id,$token,'keep_source',true)===true,'explicit critical confirmation saved');
$active=GML_Item_Resolution::snapshot($critical_id,$m->id);
gml_db_assert((int)$active['decision']['critical_confirmed']===1 && (int)$active['decision']['actor']===1,'critical confirmation and administrator recorded');
gml_db_assert(resolution_policy($resource)['ready'] && resolution_policy($resource)['translated_count']===0,'confirmed original SEO text is resolved, not a fake translation');
$parsed=['resource'=>$resource,'nodes'=>[['text'=>$critical,'hash'=>md5($critical),'context_type'=>'seo_title']]];
require_once getenv('GML_TEST_PRODUCT_DIR').'/includes/vendor/gml-translation-core/src/class-translator.php';
$translated=(new GML_Translation_Translator())->translate($parsed,'de');
gml_db_assert($translated['replacements'][$critical]===$critical,'runtime renders exact approved source');
GML_Item_Resolution::decide($critical_id,$m->id,GML_Item_Resolution::token($active),'revoke',false);
$asset=GML_Manual_Translation::snapshot($critical_id);
gml_db_assert(GML_Manual_Translation::save_manual($critical_id,GML_Manual_Translation::token($asset),'Deutscher technischer Titel'),'failed item saved through official manual mutation');
GML_Resource_Readiness::recalculate_resources([$m->id],['de']);
$policy=resolution_policy($resource);
gml_db_assert($policy['ready'] && $policy['manual_count']===1 && $policy['translated_count']===1 && $policy['keep_source_count']===0,'manual translation makes critical page ready and counts honestly');
$manual=GML_Manual_Translation::snapshot($critical_id)['tm'];
GML_Translation_Memory::insert_missing_batch([['source_hash'=>md5($critical),'source_text'=>$critical,'source_lang'=>'en','target_lang'=>'de','context_type'=>'seo_title','translated_text'=>'Automatic replacement','status'=>'auto']]);
gml_db_assert(GML_Manual_Translation::snapshot($critical_id)['tm']===$manual,'background missing-only write never overwrites manual');
$review=GML_Resource_Approval::get_status($resource,'de');
gml_db_assert(!is_wp_error(GML_Resource_Approval::reject($resource,'de',1,'Synthetic quality rejection',GML_Resource_Approval::expected_snapshot($review))),'current resource rejected through official review');
$token=GML_Item_Resolution::token(GML_Item_Resolution::snapshot($critical_id,$m->id));
gml_db_assert(is_wp_error(GML_Item_Resolution::decide($critical_id,$m->id,$token,'keep_source',true)) && !resolution_policy($resource)['ready'],'keep source cannot bypass current rejection');
wp_set_current_user(0);
gml_db_assert(is_wp_error(GML_Item_Resolution::decide($critical_id,$m->id,$token,'keep_source',true)),'anonymous decision denied');
wp_set_current_user(1);
$held_text='Held source '.wp_generate_uuid4();
GML_Resource_Manifest_Store::save_complete($shared,[['text'=>$held_text,'context_type'=>'text']]);
$wpdb->insert($wpdb->prefix.'gml_queue',['source_hash'=>md5($held_text),'source_text'=>$held_text,'source_lang'=>'en','target_lang'=>'de','context_type'=>'text','status'=>'failed','attempts'=>3,'created_at'=>current_time('mysql')]);
$held_id=(int)$wpdb->insert_id;
GML_Translation_Memory::insert_missing_batch([['source_hash'=>md5($held_text),'source_text'=>$held_text,'source_lang'=>'en','target_lang'=>'de','context_type'=>'text','translated_text'=>'Gehalten','status'=>'auto']]);
$held=GML_Manual_Translation::snapshot($held_id)['tm'];
gml_db_assert(GML_Translation_Memory::hold_auto_by_id($held['id'],$held),'quality hold fixture uses official path');
GML_Resource_Readiness::recalculate_resources([$m2->id],['de']);
$token=GML_Item_Resolution::token(GML_Item_Resolution::snapshot($held_id,$m2->id));
gml_db_assert(is_wp_error(GML_Item_Resolution::decide($held_id,$m2->id,$token,'keep_source',true)) && !resolution_policy($shared)['ready'],'keep source cannot release held translation');
require_once ABSPATH.'wp-admin/includes/template.php';
$_GET=['resource'=>$m2->id,'language'=>'de'];
ob_start();(new GML_Page_Workflow_Admin())->render('failures');$html=ob_get_clean();
gml_db_assert(strpos($html,'Keep source text')!==false && strpos($html,'Save Manual Translation')!==false,'real current attention view exposes human resolution controls');
gml_db_assert((int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}gml_queue WHERE id=$critical_id AND error_message='protected_term'")===1,'manual recovery retains original failure audit');
gml_db_assert($GLOBALS['gml_test_http_calls']===0,'resolution tests never call a live provider');
echo "OK item resolution database regressions\n";
