<?php
require __DIR__.'/bootstrap.php';
gml_test_product_init();
wp_set_current_user(1);
GML_Installer::activate();
update_option('gml_multilingual_enabled',true);
update_option('gml_languages',[['code'=>'de','enabled'=>true],['code'=>'fr','enabled'=>true]]);
update_option('gml_source_lang','en');
update_option('gml_page_demand_enabled',false);
global $wpdb;
$q=$wpdb->prefix.'gml_queue';
foreach([$q,GML_Resource_Manifest_Store::relation_table(),GML_Resource_Manifest_Store::manifest_table(),GML_Resource_Manifest_Store::readiness_table()] as $table) $wpdb->query("DELETE FROM $table");
$long=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>'Long tail scheduler']);
$nav=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>'Navigation scheduler']);
$home=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>'Home scheduler']);
update_option('show_on_front','page'); update_option('page_on_front',$home);
register_nav_menu('primary','Primary');
$menu=wp_create_nav_menu('Scheduler regression');
wp_update_nav_menu_item($menu,0,['menu-item-object-id'=>$nav,'menu-item-object'=>'page','menu-item-type'=>'post_type','menu-item-status'=>'publish']);
set_theme_mod('nav_menu_locations',['primary'=>$menu]);
update_option('gml_priority_menu_location','primary');
$resources=[]; $ids=[];
foreach([$home,$nav,$long] as $id) {
    $resource=GML_Resource_Identity::for_post($id);
    $text='Scheduler source '.$id;
    GML_Resource_Manifest_Store::save_complete($resource,[['text'=>$text,'context_type'=>'text']]);
    $resources[$id]=GML_Resource_Manifest_Store::get_by_key($resource->get_key());
    $wpdb->insert($q,['source_hash'=>md5($text),'source_text'=>$text,'source_lang'=>'en','target_lang'=>'de','context_type'=>'text','status'=>'pending','priority'=>0,'attempts'=>0,'created_at'=>current_time('mysql')]);
    $ids[$id]=(int)$wpdb->insert_id;
}
gml_db_assert(array_slice(GML_Page_Work_Scheduler::important_post_ids(),0,2)===[$home,$nav],'homepage and direct primary navigation discovered before older long-tail IDs');
delete_option(GML_Page_Work_Scheduler::WINDOW);
$selected=GML_Page_Work_Scheduler::select_items('',10);
gml_db_assert((int)$selected[0]->id===$ids[$home],'page scheduler starts with home');
$wpdb->update($q,['priority'=>1000],['id'=>$ids[$long]]);
$selected=GML_Page_Work_Scheduler::select_items('',10);
gml_db_assert((int)$selected[0]->id===$ids[$long],'manual priority preempts an existing home window');
$wpdb->update($q,['priority'=>0],['id'=>$ids[$long]]);
$selected=GML_Page_Work_Scheduler::select_items('',10);
gml_db_assert((int)$selected[0]->id===$ids[$long],'bounded page window continues instead of jumping every batch');
delete_option(GML_Page_Work_Scheduler::WINDOW);
$wpdb->update($q,['created_at'=>gmdate('Y-m-d H:i:s',time()-90*DAY_IN_SECONDS)],['id'=>$ids[$long]]);
gml_db_assert((int)GML_Page_Work_Scheduler::select_items('',10)[0]->id===$ids[$long],'aged low-traffic page eventually outranks fresh homepage demand');
$wpdb->update($q,['created_at'=>current_time('mysql')],['id'=>$ids[$long]]);
$wpdb->update($q,['status'=>'completed'],['id'=>$ids[$home]]);
delete_option(GML_Page_Work_Scheduler::WINDOW);
$demand=static function($scores,$resource_ids) use($resources,$long){$scores[$resources[$long]->id]['en']=300; return $scores;};
add_filter('gml_page_demand_scores',$demand,10,2);
gml_db_assert((int)GML_Page_Work_Scheduler::select_items('',10)[0]->id===$ids[$long],'existing source-language aggregate raises target-page demand');
remove_filter('gml_page_demand_scores',$demand,10);
$wpdb->query($wpdb->prepare("DELETE FROM {$wpdb->options} WHERE option_name LIKE %s",$wpdb->esc_like(GML_Page_Cache::CLUSTER_PREFIX).'%'));
$rid=(int)$resources[$long]->id;
GML_Page_Cache::invalidate_resources([$rid]);
add_filter('wp_doing_cron','__return_true');
$calls=[]; $fail=true; $race=false;
$adapter=static function($url,$cluster) use(&$calls,&$fail,&$race,$rid){
    $calls[]=$url;
    if($race) { $race=false; GML_Page_Cache::invalidate_resources([$rid]); }
    return !$fail;
};
$adapters=static function() use($adapter){return ['fixture'=>$adapter];};
add_filter('gml_resource_cluster_cache_adapters',$adapters);
GML_Resource_Cache_Worker::run();
gml_db_assert(count(GML_Page_Cache::pending_clusters())===1,'failed exact adapter keeps durable invalidation pending');
$fail=false; $race=true;
GML_Resource_Cache_Worker::run();
gml_db_assert(count(GML_Page_Cache::pending_clusters())===1,'concurrent new token cannot be acknowledged by an old purge');
GML_Resource_Cache_Worker::run();
gml_db_assert(GML_Page_Cache::pending_clusters()===[],'successful retry consumes exact current cluster');
$languages=[];
foreach(['de','fr','es','ru','it','pt','ja','ko','zh','ar','hi','tr','nl','pl','sv','da','fi','no','cs','el','he','uk','ro','hu'] as $code) $languages[]=['code'=>$code,'enabled'=>true];
update_option('gml_languages',$languages);
// Changing language configuration invalidates every fixture resource; isolate this cluster.
$wpdb->query($wpdb->prepare("DELETE FROM {$wpdb->options} WHERE option_name LIKE %s",$wpdb->esc_like(GML_Page_Cache::CLUSTER_PREFIX).'%'));
GML_Page_Cache::invalidate_resources([$rid]);
$plan=GML_Page_Cache::pending_clusters()[0]; $total=count($plan['urls']);
$calls=[];
GML_Resource_Cache_Worker::run();
gml_db_assert($total>20 && count($calls)===20 && count(GML_Page_Cache::pending_clusters())===1,'high-fanout cluster stops after 20 URLs');
GML_Resource_Cache_Worker::run();
gml_db_assert(count($calls)===$total && count(array_unique($calls))===$total && GML_Page_Cache::pending_clusters()===[],'token-bound cursor completes without repeating successful URLs');
gml_db_assert($GLOBALS['gml_test_http_calls']===0,'scheduler and cache mock tests make no external calls');
echo "OK page scheduling and cache consumer\n";
